# Generated by Django 3.2.10 on 2023-11-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ1', models.CharField(max_length=100)),
                ('champ2', models.IntegerField()),
            ],
        ),
    ]
